app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/hamzademo
    username: postgres
    password: password
    pool-size: 30
server:
  port: 3001
spring:
  security:
    user:
      name: admin
      password: pass123